modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/3arthqu4ke/HMC-Specifics/issues"
license = "MIT"

[[mods]]
modId = "headlessmc"
version = "${version}"
displayName = "HMC-Specifics"
authors = "3arthqu4ke"
description = '''
    1.21 implementation of the headlessmc runtime
'''

[[dependencies.headlessmc]]
modId = "minecraft"
type="required"
versionRange = "[1.21,1.21.1)"
ordering = "NONE"
side = "BOTH"
