modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/3arthqu4ke/HMC-Specifics/issues"
license = "MIT"

[[mods]]
modId = "headlessmc"
version = "1.8.1"
displayName = "HMC-Specifics"
authors = "3arthqu4ke"
description = '''
    1.20.6 implementation of the headlessmc runtime
'''

[[dependencies.headlessmc]]
modId = "minecraft"
type="required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"
